packages:
  - packages/*
  - apps/*

catalog:
  express: 5.2.1
  mongoose: 9.1.5
  "@types/express": 5.0.6
  "@types/node": 25.2.0
  "@redis/client": 5.10.0
  prom-client: 15.1.3
  http-proxy-middleware: 3.0.5
