packages:
  - packages/*
  - apps/*

catalog:
  '@redis/client': 5.10.0
  '@types/express': 5.0.6
  '@types/node': 25.2.0
  express: 5.2.1
  http-proxy-3: 1.23.2
  http-proxy-middleware: 3.0.5
  mongoose: 9.1.5
  prom-client: 15.1.3
  turbo: 2.8.2
  typescript: 5.9.3
  vitest: 4.0.18

onlyBuiltDependencies:
  - esbuild
